[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "docs_classifier"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "huggingface_hub",
    "pillow",
    "pandas", 
    "pytesseract"
]

[project.optional-dependencies]
notebook = [
    "ipykernel",
    "matplotlib",
    "opencv-python"
]


[tool.setuptools.packages.find]
include = ["docs_classifier*"]